language: node_js
node_js:
  - "5"
before_script:
  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar"
  - "java -jar selenium-server-standalone-2.53.0.jar > /dev/null &"
  - sleep 10
